# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: paymentservice/Dockerfile
    ports:
      - 5103:5103
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
